Create taskD.cpp
mikalinin/FPMI_algorithms pull request #7
Opened 2023-10-20 10:41 UTC by mikalinin

https://contest.yandex.ru/contest/53815/run-report/93855322/

2023-12-05 13:31 UTC, PolinaChubenko requested changes

2023-12-05 13:31 UTC, PolinaChubenko commented on 2contest/taskD.cpp
> +    stack2_size_ = 0;
у стеков есть метод .clear()

2023-12-05 13:31 UTC, PolinaChubenko commented on 2contest/taskD.cpp
> +  int stack2_size_ = 0;
а зачем отдельно хранить size, если в любой момент можно сделать `stack1_.size()`

2023-12-05 15:43 UTC, mikalinin commented on 2contest/taskD.cpp
> +    stack2_size_ = 0;
НЕТ!

2023-12-09 14:46 UTC, PolinaChubenko approved these changes

2023-12-09 14:46 UTC, PolinaChubenko commented on 2contest/taskD.cpp
> +    stack2_size_ = 0;
ладно, ты прав
обидно, что нет

2023-12-09 14:46 UTC, merged